/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "STD_TYPES.h"
#include "BIT_MATH.h"
#include "Delay_interface.h"

#include "RCC_interface.h"
#include "GPIO_interface.h"
#include "UART_interace.h"

#include "MQTT.h"
void BlinkPin(u8 PIN);
int main(void)
{
	MRCC_vInitSystemCLK();
	MRCC_vEnableClock(AHB1, _PERIPHERAL_EN_GPIOC);
	MRCC_vEnableClock(APB2, PERIPHERAL_EN_USART6);

	MGPIO_vSetPinMode(GPIOC, PIN6, ALTFN);
	MGPIO_vSetPinOutputType(GPIOC, PIN6,PUSH_PULL);
	MGPIO_vSetPinOutputSpeed(GPIOC, PIN6,VERY_HIGH_SPEED);
	MGPIO_vSetPinPullType(GPIOC, PIN6,NO_PULL);
	MGPIO_vSetPinAlternateFunction(GPIOC, PIN6,AF8);

	MGPIO_vSetPinMode(GPIOC, PIN7, ALTFN);
	MGPIO_vSetPinOutputType(GPIOC, PIN7,PUSH_PULL);
	MGPIO_vSetPinOutputSpeed(GPIOC, PIN7,VERY_HIGH_SPEED);
	MGPIO_vSetPinPullType(GPIOC, PIN7,NO_PULL);
	MGPIO_vSetPinAlternateFunction(GPIOC, PIN7,AF8);

	MGPIO_vSetPinMode(GPIOC , PIN0 , GPOUPUT);
	MGPIO_vSetPinOutputType(GPIOC , PIN0 , PUSH_PULL);
	MGPIO_vSetPinOutputSpeed(GPIOC , PIN0 , LOW_SPEED);
	MGPIO_vSetPinPullType(GPIOC , PIN0 , NO_PULL);
	MUART_vInit();
	MUART_vEnable(6);
	MQTT_Connect("asdfghjkloijhgv");
	Delay_vMsIn16MHz(1000);
	u8 connAck[4] = {0};
	MUART6_vRecieveString(connAck , 4);
	if((connAck[0] == 0x20) && (connAck[1] == 0x02) &&(connAck[2] == 0x00) && (connAck[3] == 0x00) )
	{
		BlinkPin(PIN0);
	}
	MQTT_Subscribe("Mahmoud_test");
	u8 subAck[5] = {0};
	MUART6_vRecieveString(subAck , 5);
	if ((subAck[0] == 0x90) && (subAck[1] == 0x03) && (subAck[2] == 0x00) &&(subAck[3] == 0x01) &&(subAck[4] == 0x01))
	{
		BlinkPin(PIN0);
	}
    /* Loop forever */
	while(1)
	{
		u8 pubAck[17] = {0};
		MUART6_vRecieveString(pubAck , 17);
		if(pubAck [16] == 0x41)
		{
			BlinkPin(PIN0);
		}
	}
}
void BlinkPin(u8 PIN)
{
	MGPIO_vSetPinValueDirect(GPIOC , PIN ,SET);
	Delay_vUsIn16MHzint(10000);
	MGPIO_vSetPinValueDirect(GPIOC , PIN ,RESET);
	Delay_vUsIn16MHzint(10000);
}
